tap homebrew/core
# core
brew vim --with-luajit
brew zsh --disable-etcdir
brew tmux
# develop
brew mono
brew mysql
# git
brew git
brew hub
brew tig
brew git-flow
brew gibo
brew mercurial
# util
brew mackup
brew tree
brew jq
brew plantuml

tap caskroom/cask
# core
cask iterm2
cask google-chrome
# develop
cask java # デフォルトで入ってない？android-sdkを使うために必要
cask mamp
cask rdm
cask sequel-pro
# editor
cask coda
cask eclipse-java
cask visual-studio-code
# virtual environment
cask virtualbox
cask vagrant
# util
cask dropbox
cask evernote
cask skype
cask skitch
cask clipmenu
cask notational-velocity
cask appcleaner
cask qlmarkdown
cask xquartz # for ricty

tap caskroom/versions
cask firefox-ja
cask thunderbird-ja

tap caskroom/fonts
cask font-source-code-pro

tap homebrew/php
brew composer
brew wp-cli

tap sanemat/font
brew ricty --powerline

tap aspnet/dnx
brew dnvm

# App Store applications
appstore 1024640650 CotEditor
appstore 409183694 Keynote
appstore 539883307 LINE
appstore 409201541 Pages
appstore 407963104 Pixelmator
appstore 692867256 Simplenote
